[tool.poetry]
name = "bright-future-ml"
version = "0.1.0"
description = "ML training pipeline for precipitation prediction"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
